# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib_with_condition(maximum: int, condition):
    last = 0
    current = 1
    result = 0
    while current < maximum:
        following = last + current
        if condition(following):
            print(following)
            result = result + following
        last = current
        current = following
    return result

def is_even(number: int):
    return number % 2 == 0

def ends_with_nine(number: int):
    return number % 10 == 9


print(fib_with_condition(4000000, is_even))
